### ISSUE TITLE
Themenplanung

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#1]
Anschließend an unsere bisherigen Discord-Konferenzen würde ich hier gerne nocheinmal das Thema für unser Projekt abstecken und diskutieren. Alle Punkte, bei denen wir uns einig sind können dann gerne auch ins [Wiki](https://github.com/DarioDagne/OSM-Analysis/wiki) übertragen werden. Dort habe ich schonmal die Grundstruktur der Dokumentation gestartet. Die Idee war es das Ganze in folgende Seiten zu unterteilen:

| **Titel**                         | **Aufgabe**                                                                                                |
|---------------------------------|----------------------------------------------------------------------------------------------------------|
| Home                            | Eine Startseite, von der aus alle anderen Wiki-Seiten über Links erreicht werden können                  |
| Einführung                      | Die Vorstellung unserer Idee und Umsetzungspläne (später Dokumentation des Fortschritts)                 |
| Bestehende Implementierungen    | Eine Übersicht über die externen Tools, Nugets und andere Projekte, welche wir genutzt/ gefunden haben   |
| Beispiele                       | Eine Seite für Beispielcodes zum besseren Verständnis (optional, würde ich erst später füllen)           |
| Zeitplanung und Aufgabenteilung | Eine Übersicht über unser Zeitmanagement (Deadlines, Zwischenergebnisse etc.) und unsere Aufgabenteilung |  

Ich habe diese Seiten bereits erstellt und miteinander verlinkt. Jetzt müssen sie nur noch mit Leben gefüllt werden. Dazu schlage ich folgendes Vorgehen vor:

1. Ich schreibe heute noch eine kurze Erläuterung unserer Analyse-Idee in [Einführung](https://github.com/DarioDagne/OSM-Analysis/wiki/Einf%C3%BChrung). Es wäre nett, wenn du (@Divino21) diese morgen lesen und evtl. ergänzen könntest.
2. Wir teilen uns die gestern besprochenen Tools (OSMSharp, OsmApiClient, GMap, Itinero) auf und arbeiten heraus, welche Funktionalitäten diese erfüllen können. Das wird dann direkt in [Bestehende Implementierungen](https://github.com/DarioDagne/OSM-Analysis/wiki/Bestehende-Implementierungen) dokumentiert (hier können wir das Vorgehen diskutieren).
3. Wir sprechen morgen (07.07.2021) am Abend nochmal über den aktuellen Stand und versuchen das Wiki zu vervollständigen + evtl. schon ein erstes UML-Diagramm zu erstellen, damit wir zur **Deadline am 08.07.2021** eine brauchbare Dokumentation unserer Grundidee haben.

Wenn du Änderungswünsche oder andere Ideen hast, kannst du die gerne diskutieren. Ich fange heute Abend erstmal mit der Einführung an, es wäre nett, wenn wir die Tools (unter 2.) gerecht aufteilen könnten. Ich würde gerne das mit der Visualisierung (GMap, Itinero) testen, kann aber auch noch eins der anderen Tools übernehmen, wenn du lieber diese bearbeitest.

**Comment by Divino21** [comment]
Meiner Sicht ist die Beschreibung  gut aber es fehlt noch eine kurz Erläuterung  für OsmSharp bzw. OsmApiClient.

**Comment by DarioDagne** [comment]
Wie gefordert würde ich die Idee nochmal in einen Stufenplan überführen, d.h. festlegen, was wir als "must do" und was als "nettes Extra" einführen um nicht zu viel zu machen. Ich würde das Ganze dann bis spätestens morgen Abend ins Wiki stellen.
Nachdem ich letzte Woche ein bisschen mit den Windows Forms gespielt habe. würde ich auch die Umsetzung einer GUI ersteinmal hintenan stellen und mich stattdesen auf das Wesentliche konzentrieren. 
Ich belese mich mal dazu, wie man mathematisch die Länge einer Straße aus OSM-Daten berechnen kann. Einige interessante Infos dazu habe ich schon gefunden, ich würde das aber auch gerne nochmal zusammenfassen.
@Divino21 Kannst du nochmal versuchen, ob du dieses OsmApiClient zum Laufen bekommst? Wenn das diese Woche nicht mehr klappt, würde ich vorerst OSMSharp nutzen...

**Comment by DarioDagne** [comment]
Ich habe [hier](https://github.com/DarioDagne/OSM-Analysis/wiki/Zeitplanung-&-Aufgabenteilung) nochmal die aktuelle Aufgabenteilung gelistet und einen kleinen Stufenplan erstellt. Wir sollten uns zuerst an den Aufgaben aus **Stufe 1** versuchen, wenn diese laufen, können wir unser Programm Stück für Stück um weitere Funktionalitäten ergänzen.

**Comment by DarioDagne** [comment]
Da das Thema akzeptiert wurde schließe ich diesen Issue. Weitere organisatorische Fragen können in den thematischen Issues geklärt werden.
