### ISSUE TITLE
UML-Diagramm

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#11]
Könntest du bitte die Klasse **CalculateDistance** noch zu deinem UML-Diagramm [hier ](https://github.com/DarioDagne/OSM-Analysis/wiki/Datenfilterung-und-Datengewinnung)hinzufügen?

Mein Entwurf dazu:
![UML-CalculateDistance](https://user-images.githubusercontent.com/83082655/126906104-e79a5b3b-abdc-47d5-b3a1-0295ff009429.png)

Code (PlantUML):
```
@startuml
class CalculateDistance{

- d_lat: double <<const>>
- erdradius: double <<const>>

- DegToRad(angle: double): double
- GetNodeFromNodeID(source: XmlOsmStreamSource, NodeID: long): Node
- EstimateDistancePythagoras(Node1: Node, Node2: Node): double
- EstimateDistanceSphericalCoordinates(Node 1: Node, Node2: Node): double
+ CalculateNetLength(net: Way[]): double
+ CalculateDistance()

}

hide empty members
@enduml
```

**Comment by Divino21** [comment]
Ich werde das machen

**Comment by DarioDagne** [comment]
@Divino21 Denke bitte daran dieses UML-Diagramm heute noch zu vervollständigen. Mir fehlt der _PlantUML_-Code um dies selber zu übernehmen. Die Klasse **CalculateDistance** erbt von **LoadData**:  

`CalculateDistance : LoadData`

Es gab nur kleine Änderungen in dieser Klasse, hier ist der neue Code:

```
`@startuml
class CalculateDistance{

- d_lat: double <<const>>
- erdradius: double <<const>>

- DegToRad(angle: double): double
- GetNodesFromIDs(NodeID: long[]): Node[]
- EstimateDistancePythagoras(Node1: Node, Node2: Node): double
- EstimateDistanceSphericalCoordinates(Node 1: Node, Node2: Node): double
+ CalculateNetLength(net: Way[]): double
+ CalculateDistance(filename: string)

}

hide empty members
@enduml
``

**Comment by Divino21** [comment]
Ich übernehme es

**Comment by Divino21** [comment]
Aufgabe schon erledigt

**Comment by DarioDagne** [comment]
Habe es im Wiki gesehen. Vielen Dank. Damit kann ich diesen Issue ja auch schließen...
