### ISSUE TITLE
Falsche Entfernungsmessung

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#14]
Unsere Verbesserungsidee im letzten Commit der **CalculateDistance**-Klasse hat einen sehr unschönen Nachteil: Sie liefert falsche Ergebnisse für die _CalculateNetLength()_-Methode. Dies liegt daran, dass der Befehl

```
var extractNodes = (from s in Source()
                        where s.Type == OsmSharp.OsmGeoType.Node
                        join nid in NodeID on s.Id equals nid
                        select s).ToArray();
```

einen Array liefert, welcher nach IDs sortiert ist, nicht nach der Reihenfolge der Knoten in einem _way_. Ohne diese geschlossene Auslesung aus der Datenbank ist der Code jedoch erschreckend langsam (mehrere Minuten für wenige Straßen). Tests haben ergeben, dass diese Zeit aufgrund der casts zum Datentyp **Node** auftreten und nicht durch die tatsächliche Berechnung der Entfernungen.

Ideen zur Lösung dieses Problems sind willkommen...

**Comment by DarioDagne** [comment]
Ich habe eine Lösung!

Hat mich gerade viele Nerven gekostet aber wenn man den Cast in der Liste lässt (also wie unsere Lösung gestern für _GetNodeFroIDs_) und dann noch innerhalb dieser Methode die Knoten nach den Ids im _way_ (abgelegt in _long[] NodeID_) sortiert, dann kann man diesen sortierten Array zurückgeben und erhält das gewünschte Ergebnis:

```
 // Umsortieren der ausgelesenen Knoten --> müssen mit Reihenfolge im way übereinstimmen
Node[] sortedNodes = new Node[extractNodes.Length];                

                for (int j=0; j<NodeID.Length; j++){
                  for (int k=0; k<nodes.Length; k++){
                  
                    if(nodes[k].Id == NodeID[j]){
                        sortedNodes[j]=nodes[k];
                        }

                    }
                }
```

Ich habe das commited und fahre mit der Dokumentation fort.

**Comment by Divino21** [comment]
Es ist schön, dass. du es  gelöst  hast, ich hatte auch eine Idee, aber wenn dein Stimmt dann ist es okay
