### ISSUE TITLE
Upcoming release: 27.07. 15:30 Uhr

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#15]
Die Bearbeitungszeit neigt sich dem Ende zu, in knapp 3h müssen wir ein release veröffentlichen. Ich habe dafür eine Liste fehlender Punkte zusammengestellt:

- [x] README - Kurzdokumentation / Zusammenfassung
- [x] Beispiele (gerade leere Wiki-Seite)
- [x] Dokumentation Datenfilterung
- [x] Dokumentation CalculateDistance
- [x] Automatisierte Tests (Xunit)

Es ist klar, dass im Rahmen der Zeit nicht alle Punkte vollständig erfüllt werden können. Wie bereits zu Beginn besprochen würde ich auf eine GUI vollständig verzichten. Unser Minimalziel haben wir inzwischen erreicht und (auf dem Bereich der Gilterung) sogar überschritten, sodass einem erfolgreichen Abschluss und Release nichts im Wege steht.

Ich habe bereits ein [**README.md**](https://github.com/DarioDagne/OSM-Analysis#readme) erstellt und so ausgefüllt, wie ich es mir vorgestellt habe. Bitte schaue dir das nochmal an und ändere oder ergänze es gegebenenfalls. Außerdem fände ich es gut, wenn du deinen eigenen Code noch etwas kommentieren, nicht verwendete using-Direktiven entfernen und die Dokumentation ergänzen könntest @Divino21.

**Comment by Divino21** [comment]
Ich mache  die Code_Doku und ich bin fast am Ende. Basierend auf unser Beschreibung in Wiki finde ich der README in ordnung

**Comment by DarioDagne** [comment]
Ich habe noch einen Test in _XUnit_ hinzugefügt, für mehr hat es leider nicht mehr gereicht. Die Doku ist up to date, damit steht einem publish nichts im wege

**Comment by DarioDagne** [comment]
Release: [OSM-Analysis-1.0](https://github.com/DarioDagne/OSM-Analysis/releases/tag/1.0)
