### ISSUE TITLE
Berechnung der Straßenlänge

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#2]
Dieses Issue soll dazu dienen, Fragen zur mathematischen Berechnung der Länge von Straßen (in OSM _ways_) zu diskutieren. Ich habe zum Experimentieren mit den verfügbaren Projektions- und Umrechnungsmethoden einen eigenen Branch erstellt. Meinen Fortschritt werde ich hier und im Wiki dokumentieren.

**Comment by DarioDagne** [comment]
Ich bitte um Entschuldigung für die lange Abwesenheit. Ich bin am Wochenende umgezogen und hatte dank Telekom-Fehler 5 Tage lang kein Internet. Ich setze mich jetzt sofort an die Umsetzung der mathematischen Berechnungen.

**Comment by DarioDagne** [comment]
Ich habe die unterschiedlichen Methoden zur Berechnung von Abständen von Punkten auf der Karte [hier](https://github.com/DarioDagne/OSM-Analysis/wiki/Berechnung-der-Stra%C3%9Fenl%C3%A4nge-aus-geographischen-Koordinaten) dokumentiert und würde mich jetzt um einen Test dieser Ansätze in C# kümmern. Daraus abgeleitet würde ich in Rücksprache mit dir @Divino21 eine Entscheidung dazu fällen, welche dieser Ansätze in unserem Tool verwendet werden soll. Zunächst nutze ich einen Satz an Testkoordinaten. Später hoffe ich auf eine Zuarbeit deinerseits zum Auslesen von Knoten-Koordinaten aus einem OSM-Datensatz.

**Comment by Divino21** [comment]
Alles klar, Da ich in der Zwischenzeit  Prüfung  bzw. Praktika, war ich auch Abwesend.

**Comment by Divino21** [comment]
Also bei deinem Diagram hast du quasi eine Klasse Node  erstellt aber ich glaube, dass es nicht Nötig ist, da dieser im dem API OsmSharp schon definiert ist. Du kannst einfach die beide Knoten für den Abstand Berechnung  als Parameter der Methode definieren(genauso wie bei der Methode  Entfernungsberechnung), un dieser liefert die entsprechende  Abstand  zurück. Die Entscheidung  der zu nutzender  Vorschrift für die Berechnung  soll "automatische" geschehen. Es heißt:
Es werden drei weitere Methode( Entfernungsmessung mittels Satz des Pythagoras, Entfernungsmessung mittels Satz des Pythagoras und variabler Länge und Entfernungsmessung mittels Kugelkoordinaten) definiert. 
Dann  in der Methode-Entfernungsberechnung wird analysiert, wie tatsächlich  die gegeben paar Koordinate  aussehen,  zum Beispiel ob dieser näher am Äquator liegen oder so, um zu entscheiden welche Methode zu nutzen ist.

**Comment by DarioDagne** [comment]
Ein sehr guter Einwand. Die **node**-Klasse dient hier tatsächlich nur der vereinfachten Testung meiner Algorithmen, da ich die Daten aus _OSM-Sharp_ noch nicht hatte aber trotzdem schon anfangen wollte mit der Umsetzung.
Ich arbeite noch an meiner Weg-Berechnung, es kristallisiert sich aber, dass man dort vermutlich schon mit sehr einfachen Berechnungsmodellen zum Ziel kommt, da die Knoten einer Straße sehr nahe beieinander liegen. Ich würde das trotzdem noch durchziehen und anständig dokumentieren um die entsprechenden Grenzen aufzuzeigen. Für die meisten Beispiele sollte die 2. Methode ausreichen. Das Ganze über eine Abfrage zu entscheiden ist eine gute Idee. Eventuell könnten wir einmal die Rechenzeit testen, sobald wir größere Datenmengen haben. Das Kugelkoordinatenmodell ist nicht automatisch "komplizierter" in der Implementierung, erfordert aber viele Sin- bzw. Cos-Auswertungen. Sollte das zu lange dauern, können wir anhand eines Vergleiches auch zu Gunsten der Rechendauer auf die Berücksichtigung der Erdkrümmung verzichten...

**Comment by DarioDagne** [comment]
@Divino21 Ich habe das Ganze jetzt mal in Form eines Polygonzugs getestet. Eine Reihe von **nodes** (meine Klasse, später Klasse aus _OSMSHARP_) ist in einem Array abgespeichert, durch welches iteriert wird. Für jedes Paar i-1 & i wird dann der Entfernungberechner aufgerufen. Ich ergänze das Ganze noch um einen Algorithmus zum Entscheiden, welche Methode verwendet werden soll so wie du vorgeschlagen hast.  

Findest du ansonsten die Datenstruktur so in Ordnung? Oder muss ich hier mit anderen Containern arbeiten? Meine Idee war es einen Array **ways[number_of_ways_in_selected_area]** aus den Daten zu extrahieren und darin dann jeweils wieder arrays mit den knoten zu haben way[i]--> **nodes[number_of_nodes]**. Kriegst du es hin mir dieses Format zu liefern oder hast du eine andere Idee?

**Comment by Divino21** [comment]
Ich denke, ist es machbar.

**Comment by DarioDagne** [comment]
Super, dann setze ich das so um.

**Comment by DarioDagne** [comment]
Dieser Aufgabenteil funktioniert (siehe Branch createclassCalculateDistance). Ich kümmere mich noch um eine Dokumentation, schließe aber diesen Issue schonmal. Weitere Probleme können in #7 oder einem neueren Issue besprochen werden.
