### ISSUE TITLE
Test OsmApiClient

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#3]
Wie in https://github.com/DarioDagne/OSM-Analysis/issues/1 erwähnt würde ich gerne nochmal das **OsmApiClient**-Paket testen um zu entscheiden, ob wir dieses in unserer finalen Implementierung verwenden oder nicht. Dafür habe ich einen entsprechenden Branch _OsmApiClient_Test_ erstellt, in den ich schon die Test-Schnippsel aus dem Tutorial kopiert haben, an denen wir letzte Woche gearbeitet haben. Wenn möglich, arbeite dort doch bitte nochmal weiter @Divino21 !

Fragen und Ideen können wir hier diskutieren. Ich fände es gut, wenn wir bis Donnerstag **15.07.2021** zu einer Entscheidung kämen. Freitag und am Wochenende bin ich voraussichtlich nicht erreichbar, da ich dort umziehe und in meiner neuen Wohnung erst wieder diesen Arbeitsplatz einrichten muss.

**Comment by Divino21** [comment]
Also Ich habe bereits einige Tests mit  OsmApiClient durchgeführt,  die in der entsprechenden  Branch zu finden sind. Die API funktioniert  genauso wie im  README erwähnt  wurde, dazu wird es vorausgesetzt, dass die Element-ID oder Begrenzung bekannt  ist und meine frage war: Kann ich Zugriff  auf die Koordinaten einer Element haben, wenn ich keine ID kenne, also ich kenne nur Straßennamen  oder die Name der Stadt? Da die API meine frage nicht beantwortet  hat, habe  ich auf weitere API gesucht. Ich habe  auch [Nominatim API](https://github.com/f1ana/Nominatim.API)  
 [Documentation](https://nominatim.org/release-docs/develop/api/Overview/)   genutzt, der die Möglich für [Geocoding](https://en.wikipedia.org/wiki/Address_geocoding) bietet,  aus gegeben Name (Straßennamen, Stadt Postleitzahl) oder Latitude&Longitude  die andere Infos wie die Begrenzung und Elemente-ID, Element-Type zu erhalten. Aus der Kombination  von beiden könnte ich Zugriff  auf infos von  Berlin, Dresden, Chemnitz erhalten aber für Freiberg liefert eine  n Fehler  in dieser  Zeile https://github.com/DarioDagne/OSM-Analysis/blob/baa4141bc5489eb3739ef800fc47e63e86cf329b/src/OsmData.cs#L105   
Ich vermute, dass es  keine Daten von Freiberg im [Master-Api](https://master.apis.dev.openstreetmap.org/) vorhanden  sind. Dann habe ich   **Nominatim** , **OsmSharp**  und  [Overpass API](https://wiki.openstreetmap.org/wiki/Overpass_API) kombiniert und das hat auch für Freiberg funktioniert  aber ich musste erstmal die Daten herunterladen.

**Comment by DarioDagne** [comment]
@Divino21 Ich habe deine Tests im OsmApiClient-Branch überflogen. Das sieht soweit wirklich vielversprechend aus. Verstehe ich das richtig, dass du dort mit der "bounding box" ein Rechteck um die jeweilige Stadt legst und dann so filterst, dass alle Elemente, die außerhalb liegen nicht genutzt werden?

Das mit dem Geocoding ist Spitze! Damit können wir deutlich flexibler arbeiten!

Könntest du die neuen Tools (Overpass API, Nominatim API) bitte noch ins Wiki aufnehmen (_bestehende Implementierungen_) ?

**Comment by Divino21** [comment]
@DarioDagne  Du verstehst  es richtig aber auch Element, die innerhalb  der Box liegen, können ignoriert  werden. Also es kommt  darauf an, was man wirklich will. 
Das Wiki werde ich ergänzen.

**Comment by DarioDagne** [comment]
Super, danke.

Eine erweiterte Idee: Kannst du mit den Tools auch nach einer **relation** filtern?
Ich habe gerade ein bisschen in der OSM-Datenbank gewühlt und dort diese interessante Relation gefunden:
[Stadgrenze Freiberg](https://www.openstreetmap.org/relation/416561#map=13/50.9173/13.3333)

Hiermit könnten wir noch deutlich genauer die Grenzen einer Stadt berücksichtigen als mit der bounding box.

**Comment by Divino21** [comment]
Ja kann man machen. Normalerweise  wenn man nach eine Stadt sucht, wird dieser als Relation  oder manchmal als Node(einen Punkt in der Miete der Stadt) ausgegeben. Die Datensatz(Freiberg) ist als relation also alle Node und ways sind nur innerhalb  von Freiberg.

**Comment by Divino21** [comment]
Außer  die Ways, die die Relation umfasst. Da sie auch zu den benachbarten Stadt gehören .  Sie werden als Member bezeichnet.

**Comment by DarioDagne** [comment]
So hatte ich das auch verstanden. Ich hatte bisher nur diese _location_-tags gesehen (das sind die Datenpunkte in der Stadtmitte) und mich vorhin über diese _relation_ gefreut. Dort sind zusätzlich auch Daten wie z.B. die Fläche oder die Einwohnerzahl hinterlegt. 
Das Problem mit den "geteilten" _ways_ habe ich ja auch schon erkannt. Vielleicht schaffen wir es ja davon nur die Knoten zu extrahieren, die auch in FG sind?
Lass uns das nachher mal telefonisch besprechen @Divino21 !

**Comment by DarioDagne** [comment]
Zur Filterung: [Arten von Straßen](https://wiki.openstreetmap.org/wiki/DE:Key:highway?uselang=de). Damit sollte man nach Fußwegen, Fahrradwegen und Schnellstraßen via _tags_ filtern können.

**Comment by Divino21** [comment]
> Zur Filterung: [Arten von Straßen](https://wiki.openstreetmap.org/wiki/DE:Key:highway?uselang=de). Damit sollte man nach Fußwegen, Fahrradwegen und Schnellstraßen via _tags_ filtern können.

Das ist sehr Hilfreich  für die Filterung

**Comment by DarioDagne** [comment]
Die Filterung ist zwar noch offen, die Infos von oben habe ich allerdings auch in unseren Stufenplan übernommen. Da wir für die Filterung inzwischen einen eigenen Issue haben und das OsmApiClient-Projekt erstmal auf Eis gelegt ist, schließe ich diesen Issue vorerst. Du kannst ihn gerne wiederbeleben wenn nötig, vorerst würde ich aber gerne die ordnung bewahren und die Themen klar trennen.
