### ISSUE TITLE
Datenfilterung

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#5]
Ausgehend von unserer gestrigen Diskussion würde ich das OsmApiClient-Tool vorerst werglassen und stattdessen erst einmal versuchen die Berechnungen lokal auszuführen (also mit Download der Osm-Daten).
Ich habe gerade deine Testdateien auf meinem Rechner ausprobieren wollen, hatte aber das Problem, dass dort haufenweise Fehlermeldungen auftreten, vermutlich weil ich noch nicht alle NuGets installiert habe. @Divino21 Könntest du bitte...

1. dokumentieren, welche Erweiterungen nötig sind um deinen Code zum Laufen zu bringen
2. ein **Minimalbeispiel** erstellen, welches mir nur aus einer lokalen Osm-Datei Knoten ausliest ?

Danach würde ich sagen kümmern wir uns um die **Datenfilterung**. Laut [dieser Doku](https://github.com/OsmSharp/core/tree/develop/samples/Sample.CompleteStream) sollte die Filterung bereits durchgeführt werden bevor wir die vollständigen _node_-Elemente ausgeben lassen...

**Comment by Divino21** [comment]
Ich arbeite daran aber ich glaube ich werde noch Heute schaffen

**Comment by Divino21** [comment]
Könntest du vielleicht  hier nochmal denFehlerart schreiben ?

**Comment by DarioDagne** [comment]
> 
> 
> Könntest du vielleicht hier nochmal denFehlerart schreiben ?

Folgende Fehlermeldungen habe ich bekommen:

```
D:\01_Uni\8. Semester\04_Softwareentwicklung\Alternative_Prüfungsleistung\04_Calculation_Roadlength\OSM-Analysis\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(4,12): error CS0579: Doppeltes Attribut "global::System.Runtime.Versioning.TargetFrameworkAttribute". [D:\01_Uni\8. Semester\04_Softwareentwicklung\Alternative_Prüfungsleistung\04_Calculation_Roadlength\OSM-Analysis\OSM-Analysis.csproj]
D:\01_Uni\8. Semester\04_Softwareentwicklung\Alternative_Prüfungsleistung\04_Calculation_Roadlength\OSM-Analysis\src\OsmData.cs(20,17): error CS0246: Der Typ- oder Namespacename "Node" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\01_Uni\8. Semester\04_Softwareentwicklung\Alternative_Prüfungsleistung\04_Calculation_Roadlength\OSM-Analysis\OSM-Analysis.csproj]
D:\01_Uni\8. Semester\04_Softwareentwicklung\Alternative_Prüfungsleistung\04_Calculation_Roadlength\OSM-Analysis\src\OsmData.cs(21,17): error CS0246: Der Typ- oder Namespacename "ForwardGeocoder" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\01_Uni\8. Semester\04_Softwareentwicklung\Alternative_Prüfungsleistung\04_Calculation_Roadlength\OSM-Analysis\OSM-Analysis.csproj]
```
Das sind nur einige davon. Er hat einige Funktionen deiner Pakete nicht gefunden und irgendetwas mit einem "doppelten Attribut"

**Comment by Divino21** [comment]
Der Fehler CS0246 kommt, weil Nominatim bzw  OsmSharp  nicht vorhaden sind, kannst du ein Commit machen, damit ich auch laufen lassen kann ?

**Comment by DarioDagne** [comment]
@Divino21 
```
    <PackageReference Include="OsmSharp.Core" Version="*"/>
    <PackageReference Include="OsmApiClient" Version="*"/>
    <PackageReference Include="Nominatim.API" Version="1.6.1"/>
    <PackageReference Include="OsmSharp" Version="*"/>
```

Diese Packages habe ich in **osm.csproj** inkludiert. Trotzdem kann ich dein **Program.cs** nicht ausführen.  
Ich commite deinen Branch nicht, dort habe nich nichts (zum Guten) verändert. Mein Beispiel ist im Branch Claculate_road_length!

**Comment by Divino21** [comment]
Das ist merkwürdig. Wie hast du es gemacht? hast du   zugriff auf  das branch in dein lokale Ordner?  Bei mir läuft ohne problem und ich habe gerade wieder getestet. Wenn es nicht wider funktioniert lass uns über Discord gemeinsam machen.

**Comment by DarioDagne** [comment]
keine Ahnung, an sich habeich auch nur _dotnet run_ eingegeben aber ich kümmere mich jetzt erstmal um meine Klasse, danach können wir ja nochmal an der Schnittstelle arbeiten. Kannst du das UML-Diagramm, das wir vorhin erarbeitet haben hier schonmal reinstellen? Dann würde ich meine Klasse (**CalculateDistance**) daran anpassen.

**Comment by Divino21** [comment]
Ich habe es schon  [Hier](https://github.com/DarioDagne/OSM-Analysis/wiki/Datenfilterung-und-Datengewinnung) gemacht.

**Comment by DarioDagne** [comment]
Die Filterung wurde erfolgreich umgesetzt, damit steht einem Release nichts mehr im Wege. Ich schließe diesen Issue, den Rest können wir dann an anderer Stelle nochmal klären...
