### ISSUE TITLE
Datenstruktur: nodes in ways

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#7]
@Divino21 Bei der Implementierung der **CalculateDistance**-Klasse ist mir aufgefallen, dass die Datenstruktur so, wie ich sie verstanden und in #2 beschrieben habe nicht vorliegt. Ich dachte, dass in den _ways_ direkt die _nodes_ gespeichert sind und ich somit per

```
// Beispielcode: Einlesen eines Knotens aus einem Weg
Node1 = currentWay.Nodes[n];
lat = Node1.Latitude;
lon = Node1.Longitude;
 ```  

an die Koordinaten der Knoten kommen könnte. Tatsächlich scheinen hier aber keine Knoten sondern lediglich deren IDs als _long[]_-Array hinterlegt zu sein. Daher die Frage an dich: Extrahierst du zusätzlich zu den Ways auch die Knoten? Anderenfalls kommen wir nicht an die Koordinaten. Oder habe ich das falsch verstanden? 

Ich bitte um schnelle Rückmeldung!

**Comment by Divino21** [comment]
Sorry für die zu spät Rückmeldung. Du hast es richtig verstanden, also in den  Ways sind die nur die IDs von der Knoten, dazu muss man zusätzlich  die Knoten  aus der "Datenbank" anhand  ihr IDs extrahiert  werden.

**Comment by DarioDagne** [comment]
@Divino21 weißt du wie das geht? Ist das eine Funktionalität, die ich noch in die **CalculateDistance**-Klasse übernehmen muss?  
Momentan habe ich hier eine "black box":

```
NodeID1 = currentWay.Nodes[n-1];
NodeID2 = currentWay.Nodes[n];

            // TO DO: Nodes aus nodeIDs auslesen
            // Node1 = ...[NodeID1];
            // Node2 = ...[NodeID2];
```

Das ist in der Schleife über alle _ways_ und _nodes_ . Dort wo jetzt noch **...** steht müsste ich dann halt die Daten extrahiert bekommen.

**Comment by Divino21** [comment]
Es wäre ja sinnvoll, wenn dieser Funktionalität gleich in der CalculateDistance-Klasse  anzulegen, weil die Nodes nur dort  für die Berechnung  gebraucht werden.

**Comment by Divino21** [comment]
Ich habe schon ein Beispiel,  wie die das Extrahieren aussehen  könnte.
Es fängt  hier https://github.com/DarioDagne/OSM-Analysis/blob/704b1efc96a974cc218ab8e3f9d3d26d138a7162/src/Overpass.cs#L73

**Comment by DarioDagne** [comment]
Das sieht sehr gut aus, danke. :)  
 Ich bin müde, versuche das aber morgen in meine Klasse einzubauen.

**Comment by Divino21** [comment]
Super 👌🏾

**Comment by DarioDagne** [comment]
Ich habe es geschafft!

Die Klasse CalculateDistance.cs ist jetzt fertig. Außerdem habe ich im zugehörigen Branch ein kleines Beispiel umgesetzt. Ein großes Problem: Die Berechnung der Straßenlänge dauert ziemlich lange, schon bei wenigen _ways_ muss man hier mit langen Wartezeiten rechnen. Ich vermute, dass diese Zeit nicht auf die Berechnung des Polygonzugs sondern auf das Auslesen der Knoten draufgeht, habe aber noch keinen Verbesserungsvorschlag.

Das Problem mit dem Auslesen der Nodes habe ich wiefolgt gelöst:

```
private Node GetNodeFromNodeID(XmlOsmStreamSource source, long NodeID)
{

var Nodes = from osmGeo in source where osmGeo.Type == OsmGeoType.Node select osmGeo;       // filtert nach Objekt-Typ --> liefert nur Nodes
var searchedNode = from osmGeo in Nodes where osmGeo.Id == NodeID select osmGeo;            // filtert nach gesuchter NodeID

var searchedNodeComplete = searchedNode.ToComplete();                                       // wandelt NodeID in komplettes Node-Objekt um

Node nodeObject = (Node)searchedNodeComplete.ElementAt(0);                                  // Cast zum Node

return nodeObject;                                                                          // gibt Knoten zurück

}
```

Damit wird aus einer Datenquelle ein Node-Objekt extrahiert. Wie genau diese Datenquelle aussehen muss, sollten wir noch klären.
