### ISSUE TITLE
Namenänderung 

### ISSUE THREAD

**Issue by Divino21** [DarioDagne/OSM-Analysis#8]
Also ich habe Name von Branch  OsmApiClient_Test geändert, da wir dort nicht nur OsmApiClient getestet haben, sondern die Anderen auch

**Comment by DarioDagne** [comment]
Das ist eine gute Idee. Ich habe für meine neue Klasse einen neuen Branch erstellt. Das Testprojekt habe ich als solches kenntlich gemacht und in einem eigenen Ordner im _main_-branch abgelegt.
