### ISSUE TITLE
StreamSource (Xml / PBF)

### ISSUE THREAD

**Issue by DarioDagne** [DarioDagne/OSM-Analysis#9]
Wie in #7 angesprochen, benötigen wir eine Entscheidung darüber, welches Dateiformat wir für die _OSS_-Daten nutzen wollen.  

Es gibt:
* .osm.pbf (binary)
* .osm (xml)

Beide Formate brauchen beim Auslesen einen anderen Datentypen. Ich habe mich bisher auf die _.osm_-Daten beschränkt. Dadurch nutze ich als Quelle **XmlOsmStreamSource**:

`var source = new XmlOsmStreamSource(File.OpenRead("Testmap.osm"));`

Für die Nutzung von _.osm.pbf-Dateien_ müssten wir entsprechend einen **PbfOsmStreamSource** nutzen. 

Daher an dich (@Divino21) die Fragen:

1. Welches Format nutzt du für den Download und die Filterung?
2. Wie soll ich das in meiner Klasse berücksichtigen? Das angeben beider Argumente ist schwierig

**Comment by Divino21** [comment]
Ich nutze jetzt  die XML  format, aber ich glaube man kann es  dann eine Methode anlegen, wo  die Datei format überprüft  werden kann.

**Comment by DarioDagne** [comment]
ich brauche für mich noch eine Schnittstelle zwischen meinem und deinem Code. Momentan ist da die obige Zeile noch "hardgecoded", d.h. da steht explizit die Datei in der Klasse drin. Hier würde ich gerne eine Datenquelle definieren. Soll ich anstelle eines Objekts einfach den Dateipfad als String übernehmen? 

`private Node GetNodeFromNodeID(XmlOsmStreamSource source, long NodeID)`  

oder lieber  

`private Node GetNodeFromNodeID(string filepath, long NodeID)` ?

**Comment by Divino21** [comment]
Ich glaube das wird nicht nötig sein, die Daten quellen als Parameter  anzulegen. Ich habe in der Klasse LoadData was Interessantes  implementiert,  also eine Methode, die das Daten laden kümmert,  unabhängig ob der Datenformat .osm.pbf oder .XML ist. Ich kommite es noch Heute.

**Comment by DarioDagne** [comment]
Das klingt gut. Heißt das, dass wir mit
```
 var Load = new LoadData (fileName);
source = Load.OsmStreamSource;
```
die Quelle fetslegen können? Oder war das anders gemeint? Kann ich den neuen Typen _OsmStreamSource_ direkt als Variable einer Methode nutzen? 

`private Node GetNodeFromNodeID(OsmStreamSource source, long NodeID){...}` 

Bitte melde dich, wenn du mit dem Review meiner Klasse fertig bist, dann können wir die beiden Teile zusammensetzen und gemeinsam an der Schnittstelle und möglichen Problemen arbeiten.

**Comment by Divino21** [comment]
Die Methode  OsmStreamSource ist protected, source = Load.OsmStreamSource wurde nicht funktionieren. Du  kannst eine Vererbung  machen und die Methode OsmStreamSource nutzen ohne die eine Instanz  anzulegen

**Comment by DarioDagne** [comment]
Dank der Vererbung `CalculateDistance : LoadData ` ist die typunabhängige _Source()_ jetzt auch in **CalculateDistance** verfügbar. Die Tests funktionieren für beide Dateitypen.
Danke für die Zuarbeit @Divino21!
